#!/bin/bash

NAME="{{ cookiecutter.project_slug }}_celery"
DJANGODIR="/usr/local/src/{{ cookiecutter.project_slug }}"
VENVDIR="${DJANGODIR}/.venv"
USER={{ cookiecutter.project_slug }}_user
GROUP=webapps
CELERY_APP=config.celery_app

echo "Starting $NAME as `whoami`"

cd $DJANGODIR
source $VENVDIR/bin/activate

echo "Starting Celery"
exec $VENVDIR/bin/celery --app=$CELERY_APP worker --loglevel=INFO -n worker.%%h
